### ISSUE TITLE
Login module

### ISSUE THREAD

**Issue by anshulmaske** [Kelvinskell/newsread#1]
Hi @Kelvinskell,

I would be happy to contribute for the login module. Using the Flask-Login, the web app can handle users and store sessions. If you are planning to use a database - could you please let me know just in case I plan on creating a branch and implementing the login module so that it doesn't affect your tech stack.

Thanks,
Anshul M

**Comment by Kelvinskell** [comment]
Hi @Ansh743,
I'd appreciate your offer of contribution. 
You're most welcome to contribute for the login service.
I plan to use the MYSQL database for storing user credentials - user ID (The primary key - which should be auto incremented.), username, password and email address.
You might also add other user parameters as you deem fit.

I'd prefer we use GitFlow Workfkow, but if you're not comfortable with that, you could suggest another Workfkow (Forking Workfkow maybe).

I anticipate your contributions.
